### ISSUE TITLE
回复“我连接不到你的网络”

### ISSUE THREAD

**Issue by cyangshengbin** [zhayujie/chatgpt-on-wechat#1098]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.8

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wxy(个人微信, wechaty)

### 问题描述 😯

我本地浏览器使用了梯子代理，能够方位chatgpt的。按照本项目的文档步骤，运行后扫描二维码登录微信后，然后用其他微信给这个账户发消息，但是收到回复是“我连接不到你的网络”，请问这个可能是哪些原因造成，怎么解决。

### 终端日志 📒

```log
Please press confirm on your phone.
Loading the contact, this may take a little while.
Login successfully as 夜
Start auto replying.
[INFO][2023-05-15 16:39:57][wechat_channel.py:124] - Wechat login success, user_id: @8c8a125f34b934ff3b5822f06929a823e8f366e3bd723e954e4a7d720ccea6cd, nickname: 夜
[INFO][2023-05-15 16:41:03][bridge.py:30] - create bot chatGPT for chat
[INFO][2023-05-15 16:41:03][chat_gpt_bot.py:49] - [CHATGPT] query=你好
[WARNING][2023-05-15 16:41:09][chat_gpt_bot.py:138] - [CHATGPT] APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001E7F7DF39A0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
[INFO][2023-05-15 16:41:10][wechat_channel.py:187] - [WX] sendMsg=Reply(type=ERROR, content=[ERROR]
我连接不到你的网络), receiver=@86f21b179a0a03c26d1e6d93105790236ff5451d144f4c5a6f5ac0a6902d48a0
```

**Comment by lanvent** [comment]
proxy设置了吗

**Comment by yunpengchen10** [comment]
我问题和你一样，无法接入open ai。但是我在国外，应该不用连VPN啊

**Comment by HelpSourceCodeSetup** [comment]
源码搭建|代部署|不成功不收费|+V：create8080

**Comment by mufengyaa** [comment]
我遇到的问题跟你类似,但报错不太一样

`[INFO][2023-05-16 23:29:18][chat_gpt_bot.py:49] - [CHATGPT] query=你好
[WARNING][2023-05-16 23:29:19][chat_gpt_bot.py:143] - [CHATGPT] APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by ProxyError('Unable to connect to proxy', SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1125)'))))
[INFO][2023-05-16 23:29:19][wechat_channel.py:187] - [WX] sendMsg=Reply(type=ERROR, content=[ERROR]
我连接不到你的网络), receiver=@0307668c1c93b64502e164b98e6ec8e9d03fd7c232ac99d92797ac946dd2d108`

**Comment by alon-qianyue** [comment]
config 中 设置 open_ai_api_base 而不是 proxy

**Comment by alon-qianyue** [comment]
> 我问题和你一样，无法接入open ai。但是我在国外，应该不用连VPN啊
openai 用的是api_base 这个变量，需要在config中设置open_ai_api_base
api_base = os.environ.get("OPENAI_API_BASE", "https://api.openai.com/v1")

**Comment by cyangshengbin** [comment]
> > 我问题和你一样，无法接入open ai。但是我在国外，应该不用连VPN啊
> > openai 用的是api_base 这个变量，需要在config中设置open_ai_api_base
> > api_base = os.environ.get("OPENAI_API_BASE", "https://api.openai.com/v1")
参数名是api_base吗？参数值是os.environ.get("OPENAI_API_BASE", "https://api.openai.com/v1")，是这样吗

**Comment by hzqfsm** [comment]
解决了吗？我也是一样
