### ISSUE TITLE
使用官方提供的Docker镜像，启动之后使用VPN报错 Max retries exceeded

### ISSUE THREAD

**Issue by 956632862** [zhayujie/chatgpt-on-wechat#1827]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

MacOS

### 运行的python版本是?

python 3.10

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

直接拉取最新的docker镜像，运行登录微信之后，打VPN

### 终端日志 📒

```log
[INFO][2024-03-21 02:38:13][bridge.py:51] - create bot chatGPT for chat
[INFO][2024-03-21 02:38:13][chat_gpt_bot.py:49] - [CHATGPT] query=，怒号啊
[WARNING][2024-03-21 02:38:16][chat_gpt_bot.py:150] - [CHATGPT] APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1007)')))
[WARNING][2024-03-21 02:38:21][chat_gpt_bot.py:160] - [CHATGPT] 第1次重试
[WARNING][2024-03-21 02:38:26][chat_gpt_bot.py:150] - [CHATGPT] APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1007)')))
[WARNING][2024-03-21 02:38:31][chat_gpt_bot.py:160] - [CHATGPT] 第2次重试
^C%
```

**Comment by QAbot-zh** [comment]
设置一下你的代理 
![image](https://github.com/zhayujie/chatgpt-on-wechat/assets/40236765/8ca66892-f300-446d-bed7-d5a35517a655)

**Comment by Wanghh666** [comment]
> 设置一下你的代理 ![image](https://private-user-images.githubusercontent.com/40236765/315850889-8ca66892-f300-446d-bed7-d5a35517a655.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MzI5ODcsIm5iZiI6MTcxMzQzMjY4NywicGF0aCI6Ii80MDIzNjc2NS8zMTU4NTA4ODktOGNhNjY4OTItZjMwMC00NDZkLWJlZDctZDVhMzU1MTdhNjU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDA5MzEyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyZTE2N2FhNTYxMjBkMzkwNGEyNmYwZjllZmQ4ZDk4YWJlZDQ2NGYxZDA0YjAxMzE3MDFmYjk1MGMwNTEyMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.k8rWHzyKWWMFPiOutOf1AXzzgCanyMgg31iYJ1jpY50)
请问下大佬 ，这个代理如何设置？

**Comment by QAbot-zh** [comment]
> > 请问下大佬 ，这个代理如何设置？

这个要看你vpn的代理类型，比如常见的http://127.0.0.1:7890或者sock5代理

**Comment by Wanghh666** [comment]
> > > 请问下大佬 ，这个代理如何设置？
> 
> 这个要看你vpn的代理类型，比如常见的[http://127.0.0.1:7890或者sock5代理](http://127.0.0.1:7890%E6%88%96%E8%80%85sock5%E4%BB%A3%E7%90%86)

[INFO][2024-04-18 09:46:50][bridge.py:56] - create bot chatGPT for chat
[INFO][2024-04-18 09:46:50][chat_gpt_bot.py:49] - [CHATGPT] query=你好
[WARNING][2024-04-18 09:46:53][chat_gpt_bot.py:150] - [CHATGPT] APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f45fd773df0>: Failed to establish a new connection: [Errno -2] Name or service not known')))
[WARNING][2024-04-18 09:46:58][chat_gpt_bot.py:160] - [CHATGPT] 第1次重试
[WARNING][2024-04-18 09:46:58][chat_gpt_bot.py:150] - [CHATGPT] APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f45fd773610>: Failed to establish a new connection: [Errno -2] Name or service not known')))
[WARNING][2024-04-18 09:47:03][chat_gpt_bot.py:160] - [CHATGPT] 第2次重试
[WARNING][2024-04-18 09:47:03][chat_gpt_bot.py:150] - [CHATGPT] APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f45fed526b0>: Failed to establish a new connection: [Errno -2] Name or service not known')))
[INFO][2024-04-18 09:47:03][wechat_channel.py:217] - [WX] sendMsg=Reply(type=ERROR, content=[ERROR]
我连接不到你的网络),
大佬 我的是127.0.0.1:7890   还是没法连接opanai   这是我的clash本地代理的问题吧？

**Comment by sugar-orange666** [comment]
> > > > 请问下大佬 ，这个代理如何设置？
> > 
> > 
> > 这个要看你vpn的代理类型，比如常见的[http://127.0.0.1:7890或者sock5代理](http://127.0.0.1:7890%E6%88%96%E8%80%85sock5%E4%BB%A3%E7%90%86)
> 
> [INFO][2024-04-18 09:46:50][bridge.py:56] - create bot chatGPT for chat [INFO][2024-04-18 09:46:50][chat_gpt_bot.py:49] - [CHATGPT] query=你好 [WARNING][2024-04-18 09:46:53][chat_gpt_bot.py:150] - [CHATGPT] APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f45fd773df0>: Failed to establish a new connection: [Errno -2] Name or service not known'))) [WARNING][2024-04-18 09:46:58][chat_gpt_bot.py:160] - [CHATGPT] 第1次重试 [WARNING][2024-04-18 09:46:58][chat_gpt_bot.py:150] - [CHATGPT] APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f45fd773610>: Failed to establish a new connection: [Errno -2] Name or service not known'))) [WARNING][2024-04-18 09:47:03][chat_gpt_bot.py:160] - [CHATGPT] 第2次重试 [WARNING][2024-04-18 09:47:03][chat_gpt_bot.py:150] - [CHATGPT] APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f45fed526b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))) [INFO][2024-04-18 09:47:03][wechat_channel.py:217] - [WX] sendMsg=Reply(type=ERROR, content=[ERROR] 我连接不到你的网络), 大佬 我的是127.0.0.1:7890 还是没法连接opanai 这是我的clash本地代理的问题吧？

我也是这样
