### ISSUE TITLE
代理能正常连上，310的方法我也试了，为啥只有项目连不上openai

### ISSUE THREAD

**Issue by liangxuannb** [zhayujie/chatgpt-on-wechat#1870]
### 前置确认

- [X] 我确认我运行的是最新版本的代码，并且安装了所需的依赖，在[FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Docker

### 运行的python版本是?

python 3.7

### 使用的chatgpt-on-wechat版本是?

Latest Release

### 运行的`channel`类型是?

wx(个人微信, itchat)

### 复现步骤 🕹

docker容器是不是有点问题，为啥我正常外部代理已经没问题了。一跑程序就不行。

### 问题描述 😯

curl可以正常，proxy的配置也开了，为啥只有项目连不上。310的内容我都看过了。
[WARNING][2024-03-30 16:44:39][chat_gpt_bot.py:150] - [CHATGPT] APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fedc0fbfbe0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[WARNING][2024-03-30 16:44:44][chat_gpt_bot.py:160] - [CHATGPT] 第1次重试
[INFO][2024-03-30 16:49:49][chat_gpt_bot.py:49] - [CHATGPT] query=治疗失眠的方式
[WARNING][2024-03-30 16:51:17][chat_gpt_bot.py:150] - [CHATGPT] APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fedc2b87dc0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

### 终端日志 📒

[root@iZaxght2minwcvZ ~]# curl http://httpbin.org/ip
{
  "origin": "51.81.168.59"
}
[root@iZaxght2minwcvZ ~]# curl api.openai.com
{
    "message": "Welcome to the OpenAI API! Documentation is available at https://platform.openai.com/docs/api-reference"
}[root@iZaxght2minwcvZ ~]#

**Comment by liangxuannb** [comment]
没问题了，注意用docker的时候，要把docker-compose.yml的时候要把environment:字段内容给改了，包括代理！！！这里的配置是最高优先级的覆盖，坑啊，我觉得不如删了试试，只用config.json的。
docker容器的网络模式我用的host模式。
如果bridge模式，我始终在容器内部无法访问到宿主机的除了映射端口外的端口（host.docker.internal:XXXX(代理服务端口)），所以无法访问到代理服务的端口。也不能靠端口映射到代理服务的端口，因为已经被代理服务占用。
 如果有懂行的朋友可以这里回复一下，bridge模式下如何连宿主机代理服务端口。问题我就先不关了。

**Comment by Wanghh666** [comment]
可以具体说下吗？我的也是这中情况：
[INFO][2024-04-23 09:31:24][chat_gpt_bot.py:49] - [CHATGPT] query=你好
[WARNING][2024-04-23 09:31:27][chat_gpt_bot.py:150] - [CHATGPT] APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f39561fbfa0>: Failed to establish a new connection: [Errno 111] Connection refused')))
[WARNING][2024-04-23 09:31:32][chat_gpt_bot.py:160] - [CHATGPT] 第1次重试
[WARNING][2024-04-23 09:31:32][chat_gpt_bot.py:150] - [CHATGPT] APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f39561fb790>: Failed to establish a new connection: [Errno 111] Connection refused')))
[WARNING][2024-04-23 09:31:37][chat_gpt_bot.py:160] - [CHATGPT] 第2次重试
[WARNING][2024-04-23 09:31:37][chat_gpt_bot.py:150] - [CHATGPT] APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f39577597e0>: Failed to establish a new connection: [Errno 111] Connection refused')))
[INFO][2024-04-23 09:31:37][wechat_channel.py:217] - [WX] sendMsg=Reply(type=ERROR, content=[ERROR]

**Comment by Wanghh666** [comment]
> 没问题了，注意用docker的时候，要把docker-compose.yml的时候要把environment:字段内容给改了，包括代理！！！这里的配置是最高优先级的覆盖，坑啊，我觉得不如删了试试，只用config.json的。 docker容器的网络模式我用的host模式。 如果bridge模式，我始终在容器内部无法访问到宿主机的除了映射端口外的端口（host.docker.internal:XXXX(代理服务端口)），所以无法访问到代理服务的端口。也不能靠端口映射到代理服务的端口，因为已经被代理服务占用。 如果有懂行的朋友可以这里回复一下，bridge模式下如何连宿主机代理服务端口。问题我就先不关了。

可以具体说下吗？我的也是这中情况：
[INFO][2024-04-23 09:31:24][chat_gpt_bot.py:49] - [CHATGPT] query=你好
[WARNING][2024-04-23 09:31:27][chat_gpt_bot.py:150] - [CHATGPT] APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f39561fbfa0>: Failed to establish a new connection: [Errno 111] Connection refused')))
[WARNING][2024-04-23 09:31:32][chat_gpt_bot.py:160] - [CHATGPT] 第1次重试
[WARNING][2024-04-23 09:31:32][chat_gpt_bot.py:150] - [CHATGPT] APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f39561fb790>: Failed to establish a new connection: [Errno 111] Connection refused')))
[WARNING][2024-04-23 09:31:37][chat_gpt_bot.py:160] - [CHATGPT] 第2次重试
[WARNING][2024-04-23 09:31:37][chat_gpt_bot.py:150] - [CHATGPT] APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f39577597e0>: Failed to establish a new connection: [Errno 111] Connection refused')))
[INFO][2024-04-23 09:31:37][wechat_channel.py:217] - [WX] sendMsg=Reply(type=ERROR, content=[ERROR]

**Comment by liangxuannb** [comment]
> > 没问题了，注意用docker的时候，要把docker-compose.yml的时候要把environment:字段内容给改了，包括代理！！！这里的配置是最高优先级的覆盖，坑啊，我觉得不如删了试试，只用config.json的。 docker容器的网络模式我用的host模式。 如果bridge模式，我始终在容器内部无法访问到宿主机的除了映射端口外的端口（host.docker.internal:XXXX(代理服务端口)），所以无法访问到代理服务的端口。也不能靠端口映射到代理服务的端口，因为已经被代理服务占用。 如果有懂行的朋友可以这里回复一下，bridge模式下如何连宿主机代理服务端口。问题我就先不关了。
> 
> 可以具体说下吗？我的也是这中情况： [INFO][2024-04-23 09:31:24][chat_gpt_bot.py:49] - [CHATGPT] query=你好 [WARNING][2024-04-23 09:31:27][chat_gpt_bot.py:150] - [CHATGPT] APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f39561fbfa0>: Failed to establish a new connection: [Errno 111] Connection refused'))) [WARNING][2024-04-23 09:31:32][chat_gpt_bot.py:160] - [CHATGPT] 第1次重试 [WARNING][2024-04-23 09:31:32][chat_gpt_bot.py:150] - [CHATGPT] APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f39561fb790>: Failed to establish a new connection: [Errno 111] Connection refused'))) [WARNING][2024-04-23 09:31:37][chat_gpt_bot.py:160] - [CHATGPT] 第2次重试 [WARNING][2024-04-23 09:31:37][chat_gpt_bot.py:150] - [CHATGPT] APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f39577597e0>: Failed to establish a new connection: [Errno 111] Connection refused'))) [INFO][2024-04-23 09:31:37][wechat_channel.py:217] - [WX] sendMsg=Reply(type=ERROR, content=[ERROR]

docker-compose.yml写好PROXY即可 ，桥连模式我不知道为啥会连不上网

**Comment by qq910696606** [comment]
docker-compose.yml写好PROXY，我写了怎么么不行，求指教，#2338

**Comment by qq910696606** [comment]
docker-compose.yml写好PROXY我也不行，可以帮忙看看吗？谢谢！#2338
