### ISSUE TITLE
sdwebiu这个插件怎么用？

### ISSUE THREAD

**Issue by Yonghongwei** [zhayujie/chatgpt-on-wechat#622]
### 前置确认

1. 网络能够访问openai接口
2. python 已安装：版本在 3.7 ~ 3.10 之间，依赖已安装
3. 在已有 issue 中未搜索到类似问题
4. [FAQS](https://github.com/zhayujie/chatgpt-on-wechat/wiki/FAQs) 中无类似问题

### 问题描述

sdwebiu这个插件该怎么用，目前发现好像并没用用sd来生成图像，用的好像是openai自己的dalle2.

### 终端日志 (如有报错)

```
[在此处粘贴终端日志]
```

### 环境

 - 操作系统类型  (Linux)：
 - Python版本  3.10.6 ( 执行 `python3 -V` )：                      
 - pip版本  22.0.2 ( 依赖问题此项必填，执行 `pip3 -V`)：

**Comment by lanvent** [comment]
see https://github.com/zhayujie/chatgpt-on-wechat/tree/master/plugins/sdwebui, 
检查本地能否访问http://127.0.0.1:7860/docs

**Comment by xgd561** [comment]
> see https://github.com/zhayujie/chatgpt-on-wechat/tree/master/plugins/sdwebui , 检查本地能否访问http://127.0.0.1:7860/docs

还是不明白，http://127.0.0.1:7860/docs是指部署的服务器上有docs这个文件夹吗？

**Comment by xgd561** [comment]
[INFO][2023-03-28 21:50:16][sdwebui.py:44] - [SD] image_query=一张猫咪的图片
[WARNING][2023-03-28 21:50:16][sdwebui.py:75] - [SD] keyword not matched: 一张猫咪的图片
[INFO][2023-03-28 21:50:16][sdwebui.py:81] - [SD] cover options={'sd_model_checkpoint': 'perfectWorld_v2Baked'}
[ERROR][2023-03-28 21:50:16][sdwebui.py:95] - [SD] exception: HTTPConnectionPool(host='127.0.0.1', port=7860): Max retries exceeded with url: /sdapi/v1/options (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f69c46e2f70>: Failed to establish a new connection: [Errno 111] Connection refused'))
[INFO][2023-03-28 21:50:16][bridge.py:28] - create bot chatGPT for chat
[INFO][2023-03-28 21:50:16][chat_gpt_bot.py:135] - [OPEN_AI] image_query=一张猫咪的图片

**Comment by xgd561** [comment]
[INFO][2023-03-28 21:57:16][sdwebui.py:44] - [SD] image_query=高清:猫咪照片
[INFO][2023-03-28 21:57:16][sdwebui.py:81] - [SD] cover options={'sd_model_checkpoint': 'perfectWorld_v2Baked'}
[ERROR][2023-03-28 21:57:16][sdwebui.py:95] - [SD] exception: HTTPConnectionPool(host='127.0.0.1', port=7860): Max retries exceeded with url: /sdapi/v1/options (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f69c29c8b50>: Failed to establish a new connection: [Errno 111] Connection refused'))
[INFO][2023-03-28 21:57:16][chat_gpt_bot.py:135] - [OPEN_AI] image_query=高清:猫咪照片
